-- 06.14 서브쿼리

-- 1) SELECT 절에 : SCALAR SUBQUERY

SELECT ENAME, (SELECT DNAME 
               FROM DEPT 
               WHERE EMP.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP;

-- 2) FROM 절에 : INLINE VIEW(TABLE SUBQUERY)

SELECT ENAME, DNAME
FROM EMP ... KEEP

-- 3) WHERE 절에 : NESTED SUBQUERY(PREDICATE SUBQUERY)