-- 06.11

-- JOIN


-- CROSS JOIN: ANSI JOIN (FROM 절에 명시)
-- 스키마들의 합 : 집합의 곱 연산과 같다.
-- A={1,2} B={3,4} 일 때, AXB -> {1,3},{1,4},{2,3},{2,4}

-- 카티샨 프로덕트 :
-- 두 테이블에 속한 튜플들의 모든 가능한 쌍을 생성함
SELECT *
FROM EMP, DEPT;




-- 동등 조인: EQUI JOIN
-- 보통 외래키 = 기본키 조건을 많이 씀
SELECT * 
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DNAME, E.ENAME;

-- EQUI 조인을 사용하여 SCOTT 사원의 부서번호와 부서 이름을 출력하시오.

SELECT E.ENAME, D.DEPTNO, DNAME
FROM DEPT D, EMP E
WHERE E.ENAME = 'SCOTT' AND D.DEPTNO = E. DEPTNO;




-- 세타 조인: NON-EQUI JOIN
-- 동등이 아닌, 일반적인 조인들

SELECT ENAME, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY SAL;

SELECT ENAME, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE=3;




-- SELF JOIN : 자기 자신을 조인 (참조)
-- EMP > MGR 칼럼이 EMP.EMPNO 참조

SELECT E.ENAME || '의 메니저는' || M.ENAME || '입니다.'
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO;

SELECT E.EMPNO, E.ENAME, E.MGR, M.ENAME
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO(+); -- 오라클에서 NULL표현




-- 다중 조인

SELECT O.ORDERID, C.NAME, B.BOOKNAME
FROM BOOK B, CUSTOMER C, ORDERS O
WHERE B.BOOKID = O.BOOKID AND C.CUSTID = O.CUSTID
ORDER BY ORDERID;



-- ANSI JOIN: 조인 조건을 FROM 절에 작성함 
-- (FROM TABLE 1 ANSI JOIN TABLE2 ON 제약조건) 
-- 1) CROSS JOIN
-- 2) INNER JOIN - USING , NATURAL JOIN
-- 3) OUTER JOIN


-- 1) CROSS JOIN

SELECT *
FROM BOOK, CUSTOMER, ORDERS;

SELECT *
FROM BOOK CROSS JOIN CUSTOMER CROSS JOIN ORDERS
ORDER BY ORDERID;


-- 2) INNER JOIN

SELECT *
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

-- 비교하는 컬럼의 이름이 같을 때
-- ON 절을 생략하고 USING을 사용하면 간단히 표현가능
SELECT *
FROM EMP INNER JOIN DEPT
USING (DEPTNO);

-- NATURAL JOIN: 알아서 컬럼이름이 동일한 컬럼을 조인조건을 설정하여 조인함
SELECT *
FROM EMP NATURAL JOIN DEPT;
