-- 06.16
-- Sequence: 숫자를 생성하는 객체
-- 설정을 통해 '일련번호'를 생성
-- 기본키가 대리키일 때 사용

-- SEQUENCE 생성하기
CREATE SEQUENCE PIB_IDX_PK;

CREATE SEQUENCE PIB_IDX_PK
START WITH 1
INCREMENT BY 1;

-- SEQUENCE 삭제하기
DROP SEQUENCE PIB_IDX_PK;

-- CURRVAL & NEXTVAL 
SELECT PIB_IDX_PK.CURRVAL 
FROM DUAL;

SELECT PIB_IDX_PK.NEXTVAL
FROM DUAL;

-- INSERT문에 넣어보기
INSERT INTO phoneinfo_basic
VALUES (PIB_IDX_PK.NEXTVAL, 
'PARK', '010-1234-1234', 'PARK@NAVER.COM', 'LONDON', SYSDATE);

-- 확인하기
SELECT *
FROM phoneinfo_basic;

-- 삭제했다가 다시 넣어보기
DELETE FROM phoneinfo_basic;

--> 시퀀스 값은 삭제했다가 넣어도 계속 증가함


--> NEXTVAL은 어떻게 초기화하나?
--> 권한만 있다면 스퀀스를 DROP하고 다시 CREATE 해도 되고,

--> 아니면 현재 값을 확인하고
SELECT LAST_NUMBER 
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME = 'PIB_IDX_PK';

--> 시퀀스의 INCREMENT를 현재 값만큼 빼도록 설정합니다.
ALTER SEQUENCE 
PIB_IDX_PK 
INCREMENT BY -1;

--> 시퀀스의 NEXTVAL값을 조회합니다.
SELECT PIB_IDX_PK.NEXTVAL 
FROM DUAL;

--> 시퀀스의 INCREMENT를 다시 1로 설정합니다.
ALTER SEQUENCE PIB_IDX_PK 
INCREMENT BY 1;









-- 17일에 다시해보기
CREATE TABLE DEPT02
AS SELECT * FROM DEPT WHERE 1=0;

SELECT * FROM DEPT02;

-- SEQUENCE 생성
CREATE SEQUENCE DEPT_DEPTNO_SEQ
START WITH 10
INCREMENT BY 10;

--DEPT03에 저장
INSERT INTO DEPT02 VALUES (DEPT_DEPTNO_SEQ.NEXTVAL
, 'DEV', 'SEOUL');





-- 대학친구, 회사 친구 테이블 기본키(대리키) 시퀀스 생성
CREATE SEQUENCE PIB_IDX_PK;
CREATE SEQUENCE PIU_IDX_PK
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE PIC_IDX_PK
START WITH 1
INCREMENT BY 1;

INSERT INTO PHONEINFO_UNIV VALUES(
PIU_IDX_PK.NEXTVAL, 'MATH', DEFAULT, 1);

-- 1. BASIC 정보입력
INSERT INTO PHONEINFO_BASIC VALUES(
PIB_IDX_PK.NEXTVAL, 'SON', '010-1111-1111', 'SON@GMAIL.COM', 'KOREA', DEFAULT);

-- 2. UNIV 정보 입력
INSERT INTO PHONEINFO_UNIV VALUES(
PIU_IDX_PK.NEXTVAL, 'COMPUTER', 4, PIB_IDX_PK.CURRVAL);

-- 3. COM 정보 입력
INSERT INTO PHONEINFO_COM VALUES(
PIC_IDX_PK.NEXTVAL, 'A_COMPANY', PIB_IDX_PK.CURRVAL);

-- 확인
SELECT *
FROM PHONEINFO_BASIC FULL OUTER JOIN PHONEINFO_UNIV
ON PHONEINFO_BASIC.IDX = PHONEINFO_UNIV.FR_REF
FULL OUTER JOIN PHONEINFO_COM
ON PHONEINFO_BASIC.IDX = PHONEINFO_COM.FR_REF;