-- 06.15

-- DDL: 데이터 정의어
-- 테이블 생성: CREATE TABLE
-- 테이블 수정: ALTER TABLE
-- 테이블 삭제: DROP TABLE

-- CREATE TABLE(컬럼이름, 타입(사이즈) [, 제약조건]...) > 컬럼 단위 제약조건
-- 또는
-- CREATE TABLE(컬럼이름, 타입(사이즈), ...
            -- [, 제약조건...]) > 테이블 단위 제약조건

CREATE TABLE EMP01(
EMPNO NUMBER(4), --사원번호
ENAME VARCHAR2(20), --사원이름
SAL NUMBER(6,2)
);

-- 서브쿼리를 이용해서 기존 테이블의 구조를 복사하고 해당 튜플도 복사
CREATE TABLE EMP02 AS SELECT * FROM EMP;
-- 제약 조건은 복사하지 않기 때문에 백업용으로 사용

-- 다른 예
CREATE TABLE EMP03 AS SELECT EMPNO, ENAME, SAL FROM EMP;
CREATE TABLE EMP04 AS SELECT * FROM EMP WHERE DEPTNO = 30;

-- 데이터 없이 스키마만 가져오는 방법
-- WHERE 절에 FALSE가 나오는 조건을 작성
CREATE TABLE EMP05 AS SELECT * FROM EMP WHERE 1=2;

-- ALTER TABLE ADD(속성명, 속성타입)
-- ALTER TABLE MODIFY()
-- ALTER TABLE DROP()

-- EMP01 테이블에 JOB컬럼을 추가해보자
ALTER TABLE EMP01 ADD(JOB VARCHAR2(9));
DESC EMP01;

-- EMP01 테이블의 JOB컬럼의 사이즈를 수정해보자
ALTER TABLE EMP01 MODIFY(JOB VARCHAR2(30));

-- EMP01 테이블의 JOB컬럼을 삭제
ALTER TABLE EMP01 DROP(JOB);

-- 모든 행을 삭제 TRUNCATE: DDL이기 때문에 롤백이 안됨
TRUNCATE TABLE EMP02;

-- 테이블의 이름 변경 -> RENAME 현재 이름 TO 새로운 이름
RENAME EMP02 TO TESTEMP;

DROP TABLE TESTEMP;
DROP TABLE EMP01;
DROP TABLE EMP02;
DROP TABLE EMP03;
DROP TABLE EMP04;
DROP TABLE EMP05;

-- 문제가 되는 예시
CREATE TABLE EMP02 
AS SELECT EMPNO, ENAME, SAL, JOB FROM EMP WHERE 1=0;

INSERT INTO EMP02(EMPNO, ENAME, SAL, JOB) 
VALUES(NULL, NULL, 10000, 'MANAGER');

-- 제약조건 걸어서 다시
CREATE TABLE EMP02(
EMPNO NUMBER(4) CONSTRAINT EMP02_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(20)  CONSTRAINT EMP02_ENAME_NN NOT NULL,
-- NOT NULL 제약은 컬럼 레벨에서만 제약조건 작성이 가능함
SAL NUMBER(6,2)  CONSTRAINT EMP02_SAL_CK CHECK (SAL>500 AND SAL <5000),
JOB VARCHAR2(20) DEFAULT '미지정',
DEPTNO NUMBER CONSTRAINT EMP02_DEPTNO_FK REFERENCES DEPT(DEPTNO)
);

INSERT INTO EMP02 VALUES(1, 'SCOTT', 1000, 'MANAGER');

DESC EMP02;

SELECT *
FROM EMP02;
